In [21]:
import pandas as pd

In [22]:
def read_dataset(dataset_path):
    """Function : reading the sharks dataset."""
    
    df = pd.read_csv(dataset_path,engine='python')
    return df

read_dataset('GSAF5.csv')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8�N, 79�W",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [23]:
def drop_columns(df):
    """Function : dropping irrelevant columns for our analysis."""
    
    #Strip column names
    for col in df.columns:
        df.rename(columns={col:col.strip(' ')},inplace=True)
#list(map(lambda x: x.strip(' '),df.columns))
      
    #Drop irrelevant columns
    cols_to_drop =\
        ['Case Number','Name','Sex','Age','Time','Investigator or Source','pdf',\
        'href formula','href','Case Number.1','Case Number.2',\
        'original order','Unnamed: 22','Unnamed: 23']
    df.drop(cols_to_drop,axis=1,inplace=True)
    
    return df

In [24]:
def drop_rows(df):
    """Function dropping irrelevant rows for our analysis.
    Studied perimeter: Australia, 1990-today."""
    
    df.Year = df.Year.astype(int) #transform year to integer to be able to select the range
    rows_to_drop = df[(df.Country!='AUSTRALIA')|(df.Year<1990)|(df.Type=='Invalid')].index
    df.drop(rows_to_drop,inplace=True) #keep the change
    
    return df

In [25]:
def fillna_values_rename_columns(df):
    """Function filling NaN values, and renaming columns
    further used in the cleaning process."""
    
    columns = ['Date','Activity','Injury','Type','Species','Area','Location','Fatal (Y/N)']
    for col in columns:
        df[col] = df[col].fillna('NA') 
        df[col] = df[col].str.lower() 
#!! df = df.fillna('NA')
#!! df= df.applymap(lambda x: x.lower() if type(x) == str else x)
    
    df.rename(columns={'Injury':'InjuryDescr'},inplace=True)
    df.rename(columns={'Fatal (Y/N)':'Fatal'},inplace=True)
    df.rename(columns={'Area':'State'},inplace=True)
#!! df.rename(columns={'Injury':'InjuryDescr','Fatal (Y/N)':'Fatal', 'Area':'State'},inplace=True)
    return df

In [62]:
def create_Month(df):
    """Function extracting months from the Date column,
    and renaming this column into 'Months'."""
    
    months = {1:'jan',2:'feb',3:'mar',4:'apr',5:'may',6:'jun',7:'jul',8:'aug',9:'sep',10:'oct',11:'nov',12:'dec'}
    for key,value in months.items():
        df.loc[df.Date.str.contains(value),'Month'] = key
    df.Month.fillna(0,inplace=True)
    df.Month = df.Month.astype(int)
    df.drop('Date',axis=1,inplace=True)
    
    return df

In [ ]:
def clean_Activity(df):
    """Function extracting activity categories from the Activity column."""
    
    activity_groups =\
        {'surfing' : ['surf'],\
        'boarding' : ['board'],\
        'diving' : ['dive','diving','spearfish'],\
        'snorkeling' : ['snorkel'],\
        'fishing' : ['fish'],\
        'swimming' : ['swim'],\
        'boating' : ['sail','row','boat','ship','yacht','kayak']}

# re.sub(r')
    for key,values in activity_groups.items():
        for value in values:
            df.loc[df.Activity.str.contains(value),'Activity'] = key
    
    df.loc[(~df.Activity.isin(activity_groups))&(df.Activity!='NA'),'Activity'] = 'other'
    
    return df

In [63]:
df =\
    create_Month(\
    fillna_values_rename_columns(\
    drop_rows(\
    drop_columns(\
    read_dataset('GSAF5.csv')\
    ))))